lib/apartment.rb
lib/apartment/adapters/abstract_adapter.rb
lib/apartment/adapters/postgresql_adapter.rb
lib/apartment/tenant.rb

In some places the connection and connection related things were being accessed directly through `ActiveRecord::Base` instead of `Apartment.connection_class`.

Retrieve connection through Apartment module

---

.travis.yml

Since a preview build is now available for JRuby 9000 it's interesting to see how this is doing on jruby-head.
I've added `jruby-head` to `allow_failures`, so it won't mark the whole build as failed if it just fails for `jruby-head`.
Docs: http://docs.travis-ci.com/user/build-configuration/

Check how this is doing on JRuby head

---

.gitignore
lib/apartment.rb
lib/apartment/adapters/abstract_adapter.rb
spec/dummy/db/seeds/import.rb
spec/tenant_spec.rb
spec/unit/config_spec.rb

Allows implementors to specify a path to seed data file. Falls back to standard Rails seed path.
* Adds test to ensure seed_data_file path is set.
* Add tests to ensure seeds are correctly imported.
* Ignore .DS_Store files.

Adds seed_data_file config option

---

lib/apartment/elevators/first_subdomain.rb
spec/unit/elevators/first_subdomain_spec.rb

When using the FirstSubDomain elevator when the super was nil it generated an error to occur. This will now return nil if super is nil.

Adding nil check in parse_tenant_name for FirstSubdomain Elevator

---

lib/apartment/elevators/generic.rb
spec/unit/elevators/domain_spec.rb
spec/unit/elevators/generic_spec.rb
spec/unit/elevators/host_hash_spec.rb
spec/unit/elevators/subdomain_spec.rb

Using `switch` and passing a block ensures that an unintended tenant does not remain selected if an error occurs (which is a potential security hole). Fixes #133, #134.

Use the block form of `switch` in the generic elevator

---

README.md
lib/apartment.rb
lib/apartment/adapters/abstract_adapter.rb
lib/apartment/adapters/abstract_jdbc_adapter.rb
lib/apartment/adapters/jdbc_mysql_adapter.rb
lib/apartment/adapters/jdbc_postgresql_adapter.rb
lib/apartment/adapters/mysql2_adapter.rb
lib/apartment/adapters/postgresql_adapter.rb
lib/generators/apartment/install/templates/apartment.rb
lib/tasks/apartment.rake
spec/adapters/mysql2_adapter_spec.rb
spec/adapters/postgresql_adapter_spec.rb
spec/examples/generic_adapter_custom_configuration_example.rb
spec/integration/apartment_rake_integration_spec.rb
spec/support/apartment_helpers.rb
spec/support/setup.rb
spec/unit/config_spec.rb

fix #264 #269 #270
It provides custom configuration for tenants which enable custom connection configuration per tenant, particularly necessary whenever tenants must live in a database on a different server than the main one.
`tenant_names` is the interface: instead of passing an array of strings, a hash is expected for custom configuration. It must follow the pattern:
config.tenant_names = {
"tenant_name" => custom_configuration_hash
}
`templates/apartment.rb` has been updated with details
I've made tests with live dbs on postgresql and mysql / no jruby tests

Custom connection options for tenants (basically to store on different servers) #264 #269 #270

---

lib/apartment/adapters/abstract_adapter.rb
spec/support/apartment_helpers.rb

Ruby 2.3.0
Rails 5.0.0.beta2
Apartment 1.0.2
When enabling seed_after_create, running the db:seed task results in an error due to the deprecated silence_stream method. This PR removes silence_stream and replaces it with silence_warning.

Change silence_stream to silence_warnings

---

lib/apartment/adapters/abstract_adapter.rb
lib/apartment/tenant.rb

One additional use case we have for multitenant applications is being able to switch additional connections to external resources (say, a search index connection or a storage bucket). We're currently triggering this logic through some hooks in the controller and/or job, but pushing it down into apartment would give us more confidence that everything is getting appropriately switched.

Add callbacks on #create and #switch!

---

lib/apartment/adapters/postgresql_adapter.rb

Trying to make tests pass for Rails 5.0 by applying a fix building on top of "Hidekazu Tanaka" PR.
This fix is to make `postgresql_adapter` recognize and clone the new Rails5 table `ar_internal_metadata` upon schema cloning. Check errors in https://travis-ci.org/influitive/apartment/builds/142076784

Rails 5.0 support - ar_internal_metadata cloning in pg_adapter

---

lib/apartment/railtie.rb

This changes skipping the initialization logic to exclude initializing
of `assets:clean` and `assets:precompile`.
This is an issue occurring when deploying to heroku where apartment
attempts to connect to the database when it is not available and causes
an error to occur.
Fixes #346

Skip initialization of Apartment during assets:clean

---

lib/apartment/adapters/abstract_adapter.rb

Fix for AbstractAdapter's DB name escaping in drop_command

---

lib/apartment/railtie.rb
spec/examples/generic_adapter_examples.rb

When the gem is initialised and a schema adapter is being used, the
adapter will initialise the schema_search_path which involves
touching the database, and thus checking out a connection for the
current thread. For threaded web servers, it is not expected that
the main thread has a database connection, so you typically set the
connection pool size equal to the number of web server threads.
This patch checks the connection back in to the pool after init so
that a web server thread can pick it up and use it.
Fixes #321

Don't retain connection used during gem initialisation

---

lib/apartment/adapters/abstract_adapter.rb

This PR enables apartment to accept DB configurations while creating a new DB (=Tenant).
Ideally, `#create_tenant` should behave same as `rake db:create` task.
**PostgreSQL**
You can specify `:owner`, `:template`, `:encoding`, `:collation`, `:ctype`, `:tablespace`, and `:connection_limit` on your database.yml.
See: [create\_database \(ActiveRecord::ConnectionAdapters::PostgreSQL::SchemaStatements\) \- APIdock](http://apidock.com/rails/ActiveRecord/ConnectionAdapters/PostgreSQL/SchemaStatements/create_database)
**MySQL**
You can specify `:charset` and `:collation` on your database.yml.
See: [create\_database \(ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter\) \- APIdock](http://apidock.com/rails/ActiveRecord/ConnectionAdapters/AbstractMysqlAdapter/create_database)

Accept DB config

---

lib/tasks/apartment.rake

The gem rake task doesn't work for me in Rails 5. Kernel#quietly was deprecated without replacement.
More info:
- http://guides.rubyonrails.org/4_2_release_notes.html
- https://github.com/rails/rails/pull/13392

Kernel#quietly was deprecated in Rails 4.2

---

README.md
lib/generators/apartment/install/templates/apartment.rb
spec/dummy_engine/config/initializers/apartment.rb

On Rails 5.0.0, the [deprecation of using strings or symbols for middleware class names](https://github.com/rails/rails/commit/83b767cef90abfc4c2ee9f4b451b0215501fae9a) was introduced. Now on rails 5.1.x [this deprecation was removed](https://github.com/rails/rails/commit/1b975e6a696655f476b10a4567b537cc92077563) so application raises an error when trying to load config/initializers/apartment.rb.
This PR solves this error on Rails 5.1.x and above by passing to middleware stack the actual elevator's class name and not a string.

Fix error on Rails 5.1.x when passing strings to the middleware stack

---

lib/apartment/adapters/abstract_adapter.rb
spec/integration/query_caching_spec.rb

When use_schemas = false, switching databases would always disable query cache. Even if it was previously enabled.
connect_to_new method was changed to check the current configuration and keep it after the new connection is established.

Keep query cache config after switching databases

---

.travis.yml
Rakefile
apartment.gemspec
docker-compose.yml
lib/apartment/adapters/postgresql_adapter.rb
spec/adapters/mysql2_adapter_spec.rb
spec/dummy/config/database.yml.sample
spec/dummy/db/migrate/20110613152810_create_dummy_models.rb
spec/dummy/db/migrate/20111202022214_create_table_books.rb
spec/examples/connection_adapter_examples.rb
spec/examples/schema_adapter_examples.rb
spec/tenant_spec.rb

@mikecmpbll 
I finally straighten out the failing spec with PostgreSQL + Rails 5.0 + Apartment that I described in #448.
The issue is caused by older PostgreSQL version (< 9.3). That version of PostgreSQL behaves a supprising behavior ([as official document described](https://www.postgresql.org/docs/9.3/static/release-9-3.html) in E.18.2.2. Other) for the cached statements.
> Force cached plans to be replanned if the search_path changes (Tom Lane)
> Previously, cached plans already generated in the current session were not redone if the query was re-executed with a new search_path setting, resulting in surprising behavior.
And the `PREPARE` statement documentation is here: https://www.postgresql.org/docs/9.3/static/sql-prepare.html
**Remarkable point:**
> Also, if the value of search_path …

PostgreSQL < 9.3 does not respect a new search_path for prepared statements

---

lib/apartment/adapters/postgresql_adapter.rb

When Postgres library (libpq) 9.6 is installed on the server, `pg_dump` adds an SQL command to SET `idle_in_transaction_session_timeout`, which is new to 9.6, so it fails when running against older versions of the Postgres database.
I've added the parameter to the blacklist.
Is this acceptable?

Fix create for libpq 9.6 and older db

---

.travis.yml
lib/apartment/adapters/postgresql_adapter.rb
spec/tenant_spec.rb
spec/unit/elevators/subdomain_spec.rb

Remove deprecated/obsolete methods/constants of Ruby, RSpec and pg.

Remove deprecation warnings

---

lib/tasks/apartment.rake

This PR fixes following issues:
- apartment:create uses deprecated method
- apartment:create has wrong task dependency
---
As described in #424, The PR commits of #55 are merged into `master` branch.
This branch fixes `development` branch about that.
And, I removed wrong task dependency.
This closes #424.

Fix an `apartment:create` task

---

README.md

To make the most of README.md, I added the gem version badge to README.md.
This is useful when the user jumps into https://rubygems.org/gems/apartment, imho.
Please feel free to reject this, if we don't need.

Add a gem version badge to README.md

---

lib/apartment.rb
lib/apartment/adapters/abstract_adapter.rb
spec/examples/generic_adapter_examples.rb

This is an implementation of #301.
Added error that is raised when apartment can't find file to be loaded.
/cc @edave, @bradrobertson 
this closes #301.

Raise FileNotFound when apartment cannot find the file to be loaded

---

lib/generators/apartment/install/templates/apartment.rb

`Apartment.use_schemas` is also used for configuring mysql2 adapter.
https://github.com/influitive/apartment/blob/8ddb79960160a4832d2a2f842d4154c010304873/lib/apartment/adapters/mysql2_adapter.rb#L7-L9

Generated initializers/apartment.rb is misguided

---

apartment.gemspec

public_suffix v3.0 has been released in Aug 4, so relax version of public_suffix gem to `>= 2`.
https://github.com/weppos/publicsuffix-ruby/releases
Changes: https://github.com/weppos/publicsuffix-ruby/compare/v2.0.5...v3.0.0

Relax version of public_suffix gem

---

README.md
lib/apartment/elevators/domain.rb
lib/apartment/elevators/host.rb
lib/generators/apartment/install/templates/apartment.rb
spec/unit/elevators/host_spec.rb

I had to use this gem for a recent project involving multiple domains pointing to a single multi-tenant Rails app. 
Naturally, I decided to use the Domain elevator to determine the tenant to switch to. However, when the client was testing the site, he used the domain of a tenant (excluding TLD) and prepended it as a subdomain of another tenant. i.e. 
Tenant A: foo.com
Tenant B: bar.com
URL visited: foo.bar.com => Switched to Tenant A
Obviously, this was not expected behaviour, and I had to go about writing a custom elevator to use the entire host to determine the tenant. Seeing that this might potentially be a common use case for multi-tenancy, I have added my custom elevator here and updated the Elevators section of the Readme to include this misconception of what the Domain elevator …

Add Host Elevator and refine Elevators documentation

---

lib/apartment/elevators/subdomain.rb

I used heroku review app.
Heroku review app's URL is "https://example-pr-1234.herokuapp.com". (example)
"herokuapp.com" is eTLD, so PublicSuffix parse to trd is nil without ignore_private option.
see: https://github.com/weppos/publicsuffix-ruby#private-domains
```
irb(main):002:0> PublicSuffix.parse("test.herokuapp.com", ignore_private: false)
=> #<PublicSuffix::Domain:0x007ffa8f9d90b8 @tld="herokuapp.com", @sld="test", @trd=nil>
irb(main):003:0> PublicSuffix.parse("test.herokuapp.com", ignore_private: true)
=> #<PublicSuffix::Domain:0x007ffa8f96e858 @tld="com", @sld="herokuapp", @trd="test">
```

Add ignore_private option to parse_host

---

gemfiles/rails_4_0.gemfile
gemfiles/rails_4_1.gemfile
gemfiles/rails_4_2.gemfile
spec/unit/elevators/host_spec.rb

Fix build failure.
Apartment development branch is randomly failing build now since #477 is merged.
Changing class variable in some examples occurs a side effect to others.
This fixes it by mocking.
And one more reason of the build failure is that [public_suffix requires ruby >= 2.1 from its 3.0.0 version](https://rubygems.org/gems/public_suffix/versions/3.0.0). So we need to strict version of public_suffix for Ruby < 2.1.0 builds.

Fix build failure

---

README.md

The db_enhancements rake task is great, but the GRANT usage command is important to ensuring that the shared_extensions schema is available. Without this, the extensions created in this space will not be available in tenant schemas.

Update README.md to include the GRANT usage command to db_enhancements

---

.travis.yml

See also: https://github.com/influitive/apartment/pull/493#issuecomment-350473091

Exclude jruby + Rails 4.0 builds from Travis-CI bulid matrix
